Ik heb nu een goede verbinding tussen de 2 projecten,het is nu ook mogelijk om de project te zien in de dashboard.Ik heb ook alle benamingen van de skeleton aangepast naar duidelijkere benamingen. ik hbe ook de data opgehaald van de rest api allen kon het nog niet laten zien in de dashboard zelf. ik heb een nieuwe component aangemaakt, serviceprovider en een command
creacoon/laravel-dashboard-jira-service-management-queues-tile pull request #1
Opened 2024-09-03 08:19 UTC by HikiMato

2024-09-05 09:03 UTC, tomcoonen commented
@HikiMato Please review all committed files and remove the draft status before asking for a review.
There are some obvious excessive files present now, and not all skeleton items/names are replaced where needed.

2024-09-05 13:30 UTC, tomcoonen requested changes
Work in progress, keep going :)

2024-09-05 13:30 UTC, tomcoonen commented on .phpunit.cache/test-results
This dir/file should not be committed

2024-09-05 13:30 UTC, tomcoonen commented on configure.php
This file is not used?

2024-09-05 13:30 UTC, tomcoonen commented on src/Facades/queue.php
> +class queue extends Facade
This file is not used? 
ps. Class names always begin with a capital letter.

2024-09-05 13:30 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +        ])->get("https://creacoon-sandbox-218.atlassian.net/rest/servicedeskapi/servicedesk/4/queue");
The host should be configurable

2024-09-05 13:30 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +        $apiEmail = 'danielsandzand@gmail.com';
Never commit any PII or credentials, move to ENV

2024-09-05 13:30 UTC, tomcoonen commented on src/JiraQueueTileStore.php
> +        $this->tile->putData('QueueInProgressStore', $data);
I think `QueueInProgressStore` needs to be more generic, since all tile data is being stored here.

2024-09-05 13:30 UTC, tomcoonen commented on tests/ExampleTest.php
Example test is meant to be replaced by a real test ofcourse

2024-09-05 13:30 UTC, tomcoonen commented on composer.json
> +        ":package_name"
Please replace all items prefixed by `:`

2024-09-05 13:30 UTC, tomcoonen commented on composer.json
> +        "rjvandoesburg/laravel-jira-rest-client": "^3.2",
This dependency is not used at the moment, remove when not needed

2024-09-06 08:51 UTC, HikiMato commented on src/JiraQueueTileStore.php
> +        $this->tile->putData('QueueInProgressStore', $data);
Could u explain more in depth about what u mean with more generic?

2024-09-09 06:08 UTC, tomcoonen requested changes
* Update README.md and make sure is holds everything to start to use the tile

2024-09-09 06:08 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +                            if ($statusId == 3 && isset($queueItem['fields']['customfield_10026']['ongoingCycle']['startTime']['iso8601'])) {
The states we want to show should not be static, define a config array to filter out the statuses we want to show.
Also make sure the sorting of the states in the config is adhered on the tile so you can order them in the config.

2024-09-09 06:08 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +                    ])->get(env('JIRA_HOST')."/rest/servicedeskapi/servicedesk/4/queue/{$queueId}/issue");
The results of this call are paginated, so when exceeding (the here undefined) page size, you will get incorrect data on your tile.

2024-09-09 06:08 UTC, tomcoonen commented on src/JiraQueueTileStore.php
This tile is specific for Jira Service Management (not Jira), so please make sure this is reflected in the naming.

2024-09-09 06:08 UTC, tomcoonen commented on resources/views/tile.blade.php
> +                        <td class="font-medium text-dimmed text-s uppercase tracking-wide tabular-nums border-b border-gray-700 ">{{ $queue['queueStatus']['open'] }}</td>
Array keys should all be snake case (or at least not be mixed).

2024-09-09 06:08 UTC, tomcoonen commented on tests/Test.php
> +namespace Creacoon\HelpscoutTile\Tests;
Wrong namespace.

2024-09-10 07:24 UTC, tomcoonen requested changes
Please spend some more time on the details like the readme, and try to think of how somebody would use this.

2024-09-10 07:24 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
>          $apiEmail = config('atlassian.jira.auth.basic.username');
You use this variable on 1 location, simply use the config directly there (also check other config usages)

2024-09-10 07:24 UTC, tomcoonen commented on README.md
> +         'helpscout' => [
This config is unrelated to this tile? Add a concrete template you can copy paste into the dashboard project.

2024-09-10 07:24 UTC, tomcoonen commented on README.md
> +In the `dashboard` config file, you must add this configuration in the `tiles` key. The `mailboxes` should contain an array of mailbox id's that you want to use on the dashboard.
Mailboxes?

2024-09-10 07:24 UTC, tomcoonen commented on README.md
> +composer require creacoon/laravel-dashboard-jira-tile
Wrong package referenced

2024-09-10 07:24 UTC, tomcoonen commented on CHANGELOG.md
> +All notable changes to `package_name` will be documented in this file.
please replace `package_name` with the package name

2024-09-10 07:24 UTC, tomcoonen commented on resources/views/tile.blade.php
> +                    <th class="font-medium text-white text-l uppercase tracking-wide tabular-nums">Queue Name</th>
The headers are dynamic based on the states coming from JSM, so this can't be static here.

2024-09-10 07:24 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +    protected $signature = 'fetch:queue-jira-data';
Please make sure the signature is in line with the other tiles and make it specific. This tile doesn't concern Jira but Jira Service Management.

2024-09-10 07:24 UTC, tomcoonen commented on src/FetchDataFromJiraQueueCommand.php
> +                        ])->get(config('atlassian.jira.host')."/rest/servicedeskapi/servicedesk/4/queue/{$queueId}/issue");
There is no pagination used for the issues, you won't have accurate counts this way.
Make sure you don't fetch resolved issues since the list can get very long.

2024-10-16 09:52 UTC, merged